=== mcho421/noj/schemas/dictionary_schema_1.0.0a.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.naturalorderjapanese.com"
    xmlns="http://www.naturalorderjapanese.com"
    elementFormDefault="qualified"
    version="1.0.0a">

    <!-- definition of simple elements -->
    <xs:element name="name" type="xs:string"/>
    <xs:element name="dump_version" type="xs:string"/>
    <xs:element name="convert_version" type="xs:string"/>
    <xs:element name="date" type="xs:string"/>
    <xs:element name="kana" type="xs:string"/>
    <xs:element name="kanji" type="xs:string"/>
    <xs:element name="accent" type="xs:string"/>
    <xs:element name="definition_text" type="xs:string"/>
    <xs:element name="expression" type="xs:string"/>
    <xs:element name="reading" type="xs:string"/>
    <xs:element name="meaning" type="xs:string"/>
    <xs:element name="sound" type="xs:string"/>
    <xs:element name="image" type="xs:string"/>

    <!-- definition of complex elements -->
    <xs:element name="extra">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="name" type="xs:string" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="dictionary_meta">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="dump_version" minOccurs="0"/>
                <xs:element ref="convert_version" minOccurs="0"/>
                <xs:element ref="date" minOccurs="0"/>
                <xs:element ref="extra" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="type" type="xs:string" default="UNKNOWN"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="usage_example">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="expression"/>
                <xs:element ref="reading" minOccurs="0"/>
                <xs:element ref="meaning" minOccurs="0"/>
                <xs:element ref="sound" minOccurs="0"/>
                <xs:element ref="image" minOccurs="0"/>
                <xs:element ref="extra" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="type" type="xs:string" default="UNKNOWN"/>
            <xs:attribute name="validated" type="xs:boolean" default="true"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="entry">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="kana" maxOccurs="unbounded"/>
                <xs:element ref="kanji" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="accent" minOccurs="0"/>
                <xs:element ref="extra" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="definition" type="definitionType" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="format" type="xs:string" default="J-E1"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="dictionary">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="dictionary_meta"/>
                <xs:element ref="entry" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="schema_version" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <!-- recursive elements -->
    <xs:complexType name="definitionType">
        <xs:sequence>
            <xs:element ref="definition_text" minOccurs="0"/>
            <xs:element ref="extra" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="usage_example" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="definition" type="definitionType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="group" type="xs:string"/>
    </xs:complexType>

</xs:schema>

=== mcho421/noj/schemas/example_dictionary_1.0.0a.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary schema_version="1.0.0a" 
    xmlns="http://www.naturalorderjapanese.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.naturalorderjapanese.com dictionary_schema_1.0.0a.xsd">

    <dictionary_meta>
        <name>example</name>
        <dump_version>1a</dump_version>
        <convert_version>1a</convert_version>
        <date>sunday</date>
        <extra name="dictextra">some extra info</extra>
    </dictionary_meta>

    <entry format="J-J1">
        <kana>い・る</kana>
        <kanji>入る</kanji>
        <accent>0</accent>
        <definition group="grammar">
            <definition_text>動ラ五［四］</definition_text>
            <definition group="meaning">
                <definition_text>人などが意図的に内側に移動する。</definition_text>
                <definition>
                    <definition_text>人などが，ある建物・区画の中に移動する。はいる。</definition_text>
                    <usage_example type="unknown">
                        <expression>無用の者―・る可(ベ)からず</expression>
                    </usage_example>
                    <usage_example type="unknown">
                        <expression>虎穴に―・らずんば虎子を得ず</expression>
                    </usage_example>
                </definition>
            </definition>
        </definition>
    </entry>
    <entry format="J-J1">
        <kana>こ・い</kana>
        <kanji>濃い</kanji>
        <accent>1</accent>
        <definition group="subdefinition">
            <definition_text>物の濃度・密度が大きい。</definition_text>
            <definition>
                <definition_text>色が深い。</definition_text>
                <usage_example type="unknown">
                    <expression>―・い緑</expression>
                </usage_example>
                <usage_example type="unknown">
                    <expression>夕闇が―・い</expression>
                </usage_example>
            </definition>
            <definition>
                <definition_text>味・匂い・化粧などが強い。</definition_text>
                <usage_example type="unknown">
                    <expression>―・い味つけにする</expression>
                </usage_example>
                <usage_example type="unknown">
                    <expression>ジャスミンの―・い香り</expression>
                </usage_example>
                <usage_example type="unknown">
                    <expression>おしろいが―・い</expression>
                </usage_example>
            </definition>
        </definition>
    </entry>
    <entry format="fake">
        <kana>こ・い</kana>
        <kanji>濃い</kanji>
        <accent>1</accent>
        <extra name="entryextra">entra entry stuff</extra>
        <definition>
            <definition_text>色が深い。</definition_text>
            <extra name="defextra">extra definition stuff</extra>
            <usage_example type="unknown" validated="false">
                <expression>some ue</expression>
                <reading>some reading</reading>
                <meaning>some meaning</meaning>
                <sound>some sound</sound>
                <image>some image</image>
                <extra name="ueextra">some extra stuff</extra>
            </usage_example>
        </definition>
    </entry>

</dictionary>
